-- ─────────────────────────────────────────────────────────────────────
-- Journey to the East — initial database schema.
--
-- How to apply:
--   1. Open the Supabase dashboard for the project
--   2. SQL Editor → New query → paste this whole file → Run
--   3. Verify tables appear under "Database → Tables"
--
-- All app tables enable Row-Level Security (RLS) and define explicit
-- policies. Public read access where it makes sense (stories, likes,
-- comments) so anonymous visitors can see content; everything else is
-- gated on `auth.uid() = user_id`.
-- ─────────────────────────────────────────────────────────────────────

-- Required for gen_random_uuid()
create extension if not exists "pgcrypto";


-- ─── profiles ────────────────────────────────────────────────────────
-- One row per authenticated user. Created automatically by the trigger
-- below on auth.users insert, so the application never has to create it.
create table if not exists public.profiles (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null unique references auth.users(id) on delete cascade,
  name         text,
  avatar_url   text,
  bio          text,
  email        text,
  telegram_username text,
  created_at   timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Anyone (including anon) can read profile rows — needed for story authors,
-- comment authors, etc. We do NOT expose email here (front-end omits it).
create policy "profiles are publicly readable"
  on public.profiles for select
  using (true);

create policy "users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = user_id);

create policy "users can update their own profile"
  on public.profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users can delete their own profile"
  on public.profiles for delete
  using (auth.uid() = user_id);


-- ─── favorites ───────────────────────────────────────────────────────
-- Generic favorite table — `item_type` is "city", "itinerary", "story"
-- and `item_id` is the slug or DB id.
create table if not exists public.favorites (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  item_type   text not null check (item_type in ('city', 'itinerary', 'story')),
  item_id     text not null,
  created_at  timestamptz not null default now(),
  unique (user_id, item_type, item_id)
);

alter table public.favorites enable row level security;

create policy "users see their own favorites"
  on public.favorites for select
  using (auth.uid() = user_id);

create policy "users add their own favorites"
  on public.favorites for insert
  with check (auth.uid() = user_id);

create policy "users remove their own favorites"
  on public.favorites for delete
  using (auth.uid() = user_id);


-- ─── saved_trips ─────────────────────────────────────────────────────
-- Output of the /budget calculator and the /chat AI tour builder.
create table if not exists public.saved_trips (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  name         text not null,
  days         int  not null check (days > 0),
  style        text not null check (style in ('Budget', 'Standard', 'Luxury')),
  cities       text[] not null default '{}',
  total_budget numeric(10, 2) not null check (total_budget >= 0),
  breakdown    jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);

alter table public.saved_trips enable row level security;

create policy "users see their saved trips"
  on public.saved_trips for select
  using (auth.uid() = user_id);

create policy "users create saved trips"
  on public.saved_trips for insert
  with check (auth.uid() = user_id);

create policy "users update their saved trips"
  on public.saved_trips for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users delete their saved trips"
  on public.saved_trips for delete
  using (auth.uid() = user_id);


-- ─── bookings ────────────────────────────────────────────────────────
-- A "Confirm booking" from the AI concierge writes a row here. The
-- reference like UZ-2026-001 is generated by the API route, not the DB.
create table if not exists public.bookings (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null references auth.users(id) on delete cascade,
  reference             text not null unique,
  tour_data             jsonb not null,
  full_name             text not null,
  phone                 text,
  notification_channel  text not null check (notification_channel in ('email', 'telegram', 'both')),
  status                text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at            timestamptz not null default now()
);

alter table public.bookings enable row level security;

create policy "users see their own bookings"
  on public.bookings for select
  using (auth.uid() = user_id);

-- Bookings are INSERTed via the /api/bookings/create route, which uses the
-- service-role client (RLS bypassed). We still allow user-owned inserts
-- as a defensive fallback.
create policy "users can create their own bookings"
  on public.bookings for insert
  with check (auth.uid() = user_id);

create policy "users update their own bookings"
  on public.bookings for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ─── stories ─────────────────────────────────────────────────────────
-- User-published travel stories. Public-readable so anon visitors can
-- browse /stories; writes are gated to the author.
create table if not exists public.stories (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  title        text not null,
  content      text not null,
  cover_image  text,
  city         text,
  likes_count  int  not null default 0,
  created_at   timestamptz not null default now()
);

alter table public.stories enable row level security;

create policy "stories are publicly readable"
  on public.stories for select
  using (true);

create policy "users can publish their own stories"
  on public.stories for insert
  with check (auth.uid() = user_id);

create policy "authors can update their stories"
  on public.stories for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "authors can delete their stories"
  on public.stories for delete
  using (auth.uid() = user_id);


-- ─── story_likes ─────────────────────────────────────────────────────
create table if not exists public.story_likes (
  id          uuid primary key default gen_random_uuid(),
  story_id    uuid not null references public.stories(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (story_id, user_id)
);

alter table public.story_likes enable row level security;

create policy "anyone can count likes"
  on public.story_likes for select
  using (true);

create policy "users like stories"
  on public.story_likes for insert
  with check (auth.uid() = user_id);

create policy "users unlike their likes"
  on public.story_likes for delete
  using (auth.uid() = user_id);


-- ─── story_comments ──────────────────────────────────────────────────
create table if not exists public.story_comments (
  id          uuid primary key default gen_random_uuid(),
  story_id    uuid not null references public.stories(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  content     text not null check (length(content) between 1 and 2000),
  created_at  timestamptz not null default now()
);

alter table public.story_comments enable row level security;

create policy "comments are publicly readable"
  on public.story_comments for select
  using (true);

create policy "users can comment"
  on public.story_comments for insert
  with check (auth.uid() = user_id);

create policy "authors can edit their comments"
  on public.story_comments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "authors can delete their comments"
  on public.story_comments for delete
  using (auth.uid() = user_id);


-- ─── ai_conversations ────────────────────────────────────────────────
-- Persisted chat transcripts. user_id is nullable so anon sessions can
-- still be recorded (the chat page allows pre-login interaction).
create table if not exists public.ai_conversations (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references auth.users(id) on delete cascade,
  messages    jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now()
);

alter table public.ai_conversations enable row level security;

create policy "users see their own conversations"
  on public.ai_conversations for select
  using (auth.uid() = user_id);

create policy "users insert their own conversations"
  on public.ai_conversations for insert
  with check (auth.uid() is null or auth.uid() = user_id);

create policy "users update their own conversations"
  on public.ai_conversations for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ─── triggers ────────────────────────────────────────────────────────

-- When a new user signs up via Supabase Auth, create a matching profile.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- Keep stories.likes_count in sync via INSERT/DELETE on story_likes.
create or replace function public.bump_story_likes()
returns trigger
language plpgsql
as $$
begin
  if (tg_op = 'INSERT') then
    update public.stories set likes_count = likes_count + 1 where id = new.story_id;
    return new;
  elsif (tg_op = 'DELETE') then
    update public.stories set likes_count = greatest(likes_count - 1, 0) where id = old.story_id;
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists story_likes_count_bump on public.story_likes;
create trigger story_likes_count_bump
  after insert or delete on public.story_likes
  for each row execute function public.bump_story_likes();


-- ─── indexes ─────────────────────────────────────────────────────────
create index if not exists favorites_user_id_idx       on public.favorites(user_id);
create index if not exists saved_trips_user_id_idx     on public.saved_trips(user_id);
create index if not exists bookings_user_id_idx        on public.bookings(user_id);
create index if not exists bookings_reference_idx      on public.bookings(reference);
create index if not exists stories_created_at_idx      on public.stories(created_at desc);
create index if not exists story_likes_story_id_idx    on public.story_likes(story_id);
create index if not exists story_comments_story_id_idx on public.story_comments(story_id);
create index if not exists ai_conv_user_id_idx         on public.ai_conversations(user_id);


-- ─── storage bucket for story cover photos ──────────────────────────
-- Run this *after* the SQL above so the public bucket exists for
-- /stories submissions. Public read so cover photos render on the
-- listing page without signed URLs.
insert into storage.buckets (id, name, public)
values ('stories', 'stories', true)
on conflict (id) do nothing;

create policy "story images are publicly readable"
  on storage.objects for select
  using (bucket_id = 'stories');

create policy "authenticated users can upload story images"
  on storage.objects for insert
  with check (bucket_id = 'stories' and auth.role() = 'authenticated');

create policy "users delete their own story images"
  on storage.objects for delete
  using (bucket_id = 'stories' and auth.uid() = owner);
